/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rlm_zmq.proto */

#ifndef PROTOBUF_C_rlm_5fzmq_2eproto__INCLUDED
#define PROTOBUF_C_rlm_5fzmq_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _FRAVP FRAVP;
typedef struct _Request Request;
typedef struct _Response Response;


/* --- enums --- */

typedef enum _RLMRCODE {
  RLM__RCODE__REJECT = 0,
  RLM__RCODE__FAIL = 1,
  RLM__RCODE__OK = 2,
  RLM__RCODE__HANDLED = 3,
  RLM__RCODE__INVALID = 4,
  RLM__RCODE__USERLOCK = 5,
  RLM__RCODE__NOTFOUND = 6,
  RLM__RCODE__NOOP = 7,
  RLM__RCODE__UPDATED = 8,
  RLM__RCODE__NUMCODES = 9,
  RLM__RCODE__UNKNOWN = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RLM__RCODE)
} RLMRCODE;
typedef enum _RLMCOMPONENT {
  RLM__COMPONENT__AUTH = 0,
  RLM__COMPONENT__AUTZ = 1,
  RLM__COMPONENT__PREACCT = 2,
  RLM__COMPONENT__ACCT = 3,
  RLM__COMPONENT__SESS = 4,
  RLM__COMPONENT__PRE_PROXY = 5,
  RLM__COMPONENT__POST_PROXY = 6,
  RLM__COMPONENT__POST_AUTH = 7,
  RLM__COMPONENT__RECV_COA = 8,
  RLM__COMPONENT__SEND_COA = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RLM__COMPONENT)
} RLMCOMPONENT;

/* --- messages --- */

struct  _FRAVP
{
  ProtobufCMessage base;
  uint32_t attr;
  protobuf_c_boolean has_vendor;
  uint32_t vendor;
  char *value;
  char *op;
  protobuf_c_boolean has_tag;
  uint32_t tag;
};
extern char fr__avp__op__default_value[];
#define FR__AVP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fr__avp__descriptor) \
    , 0, 0,0u, NULL, fr__avp__op__default_value, 0,0 }


struct  _Request
{
  ProtobufCMessage base;
  RLMCOMPONENT component;
  size_t n_request;
  FRAVP **request;
  size_t n_reply;
  FRAVP **reply;
  size_t n_control;
  FRAVP **control;
  size_t n_session_state;
  FRAVP **session_state;
  size_t n_proxy_request;
  FRAVP **proxy_request;
  size_t n_proxy_reply;
  FRAVP **proxy_reply;
  size_t n_coa;
  FRAVP **coa;
  size_t n_coa_reply;
  FRAVP **coa_reply;
  size_t n_disconnect;
  FRAVP **disconnect;
  size_t n_disconnect_reply;
  FRAVP **disconnect_reply;
};
#define REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request__descriptor) \
    , 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _Response
{
  ProtobufCMessage base;
  RLMRCODE rcode;
  size_t n_request;
  FRAVP **request;
  size_t n_reply;
  FRAVP **reply;
  size_t n_control;
  FRAVP **control;
  size_t n_session_state;
  FRAVP **session_state;
  size_t n_proxy_request;
  FRAVP **proxy_request;
  size_t n_proxy_reply;
  FRAVP **proxy_reply;
  size_t n_coa;
  FRAVP **coa;
  size_t n_coa_reply;
  FRAVP **coa_reply;
  size_t n_disconnect;
  FRAVP **disconnect;
  size_t n_disconnect_reply;
  FRAVP **disconnect_reply;
};
#define RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&response__descriptor) \
    , RLM__RCODE__NOOP, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


/* FRAVP methods */
void   fr__avp__init
                     (FRAVP         *message);
size_t fr__avp__get_packed_size
                     (const FRAVP   *message);
size_t fr__avp__pack
                     (const FRAVP   *message,
                      uint8_t             *out);
size_t fr__avp__pack_to_buffer
                     (const FRAVP   *message,
                      ProtobufCBuffer     *buffer);
FRAVP *
       fr__avp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fr__avp__free_unpacked
                     (FRAVP *message,
                      ProtobufCAllocator *allocator);
/* Request methods */
void   request__init
                     (Request         *message);
size_t request__get_packed_size
                     (const Request   *message);
size_t request__pack
                     (const Request   *message,
                      uint8_t             *out);
size_t request__pack_to_buffer
                     (const Request   *message,
                      ProtobufCBuffer     *buffer);
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator);
/* Response methods */
void   response__init
                     (Response         *message);
size_t response__get_packed_size
                     (const Response   *message);
size_t response__pack
                     (const Response   *message,
                      uint8_t             *out);
size_t response__pack_to_buffer
                     (const Response   *message,
                      ProtobufCBuffer     *buffer);
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FRAVP_Closure)
                 (const FRAVP *message,
                  void *closure_data);
typedef void (*Request_Closure)
                 (const Request *message,
                  void *closure_data);
typedef void (*Response_Closure)
                 (const Response *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    rlm__rcode__descriptor;
extern const ProtobufCEnumDescriptor    rlm__component__descriptor;
extern const ProtobufCMessageDescriptor fr__avp__descriptor;
extern const ProtobufCMessageDescriptor request__descriptor;
extern const ProtobufCMessageDescriptor response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_rlm_5fzmq_2eproto__INCLUDED */
